// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {forensic} from '../models';
import {main} from '../models';

export function CancelForensic(arg1:string):Promise<void>;

export function CheckForensic(arg1:string):Promise<forensic.Info>;

export function DeletePassword(arg1:string):Promise<void>;

export function GenerateCharlesKey(arg1:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetPassword(arg1:string):Promise<string>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PickDirectory(arg1:string,arg2:string):Promise<string>;

export function PickExecutable(arg1:string):Promise<string>;

export function RunForensic(arg1:Array<string>):Promise<string>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SetForensicBinaryPath(arg1:string):Promise<void>;
