// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelForensic(arg1) {
  return window['go']['main']['App']['CancelForensic'](arg1);
}

export function CheckForensic(arg1) {
  return window['go']['main']['App']['CheckForensic'](arg1);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function GenerateCharlesKey(arg1) {
  return window['go']['main']['App']['GenerateCharlesKey'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PickDirectory(arg1, arg2) {
  return window['go']['main']['App']['PickDirectory'](arg1, arg2);
}

export function PickExecutable(arg1) {
  return window['go']['main']['App']['PickExecutable'](arg1);
}

export function RunForensic(arg1) {
  return window['go']['main']['App']['RunForensic'](arg1);
}

export function SavePassword(arg1, arg2) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2);
}

export function SetForensicBinaryPath(arg1) {
  return window['go']['main']['App']['SetForensicBinaryPath'](arg1);
}
